name: Build

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2
      - name: Install Dependencies
        run: |
          nuget restore
      - name: Build Debug
        run: |
          msbuild
          ls SoMRandomizer\bin\Debug\net462
      - name: Store
        uses: actions/upload-artifact@v4
        with:
          name: SecretOfManaRandomizer-Debug
          path: SomRandomizer/bin/Debug/net462/SoMRandomizer.*
          if-no-files-found: error
          compression-level: 9
          retention-days: 7
